apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantum_front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quantum_front
  template:
    metadata:
      labels:
        app: quantum_front
    spec:
      containers:
        - name: quantum_front
          image: zeromaxinc/quantum_front
          ports:
            - containerPort: 3000
            
---
apiVersion: v1
kind: Service
metadata:
  name: quantum_front
spec:
  selector:
    app: quantum_front
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30013