name: Deployment workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest

    steps: 

    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Build the Docker image
      run: docker build -t quantum_front . && docker tag quantum_front zeromaxinc/quantum_front
  
    - name: Docker push
      run: docker push zeromaxinc/quantum_front


    
    - name: Log in to Server and Restarting Kubernetes
      uses: appleboy/ssh-action@master
      with:
        host: 146.190.116.39
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /root/quantumitllc
          ls
          kubectl delete -f quantum.yaml
          kubectl apply -f quantum.yaml

    
          
    - name: Configuration Git
      run: git config --global user.email "zeromax.adm@gmail.com" && git config --global user.name "zeromaxinc"
 
    - name: Notification Slack
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: QuantumITLLC
        SLACK_TITLE: About Project
        SLACK_USERNAME: Quantum'sBot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_MESSAGE: "${{ github.actor }} created commit:  Commit message: ${{ github.event.commits[0].message }}"
        
        
    - name: Telegram Notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
           ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
