name: Deployment workflow
on:
  push:
    branches: [ "main" ]

jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: >-
          --privileged
          -v /var/run/docker.sock:/var/run/docker.sock
        ports:
          - 2375:2375


    steps: 

      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        if: ${{ success() }}
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
      - name: Build the Docker image
        if: ${{ success() }}
        run: docker build -t quantum_front . && docker tag quantum_front zeromaxinc/quantum_front
    
      - name: Docker push
        if: ${{ success() }}
        run: docker push zeromaxinc/quantum_front


      
      - name: Log in to Server and Restarting Kubernetes
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: 142.93.77.97
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /root/quantumitllc/frontend
            ls
            kubectl delete -f quantumitllc.yaml
            kubectl apply -f quantumitllc.yaml

      
      - name: Notification Slack
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: QuantumITLLC
          SLACK_TITLE: About Project
          SLACK_USERNAME: Quantum'sBot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "${{ github.actor }} successfully created commit!!! ✅✅✅:  Commmit message: ${{ github.event.commits[0].message }}"


      - name: Notification Slack
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: QuantumITLLC
          SLACK_TITLE: About Project
          SLACK_USERNAME: Quantum'sBot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "${{ github.actor }}  failed created commit!!! ❌❌❌:  Commit message: ${{ github.event.commits[0].message }}"
          
          
      - name: Telegram Notifications on Success
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            ${{ github.actor }} successfully created commit ✅✅✅:
              Commit message: ${{ github.event.commits[0].message }}
              Repository: ${{ github.repository }}
              See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}


      - name: Telegram Notifications on Failure
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            ${{ github.actor }} failed created commit ❌❌❌:
              Commit message: ${{ github.event.commits[0].message }}
              Repository: ${{ github.repository }}
              See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}