name: Pull Request
on:
  pull_request:

      
jobs:
  deployment:
    name: Pull Request
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: >-
          --privileged
          -v /var/run/docker.sock:/var/run/docker.sock
        ports:
          - 2375:2375


    steps: 

      - uses: actions/checkout@v2
      - name: Notification Slack
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: QuantumITLLC
          SLACK_TITLE: About Project
          SLACK_USERNAME: Quantum'sBot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "${{ github.actor }} successfully created Pull Request!!! ✅✅✅:  Pull Request message: ${{ github.event.commits[0].message }}"


      - name: Notification Slack
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: QuantumITLLC
          SLACK_TITLE: About Project
          SLACK_USERNAME: Quantum'sBot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "${{ github.actor }}  failed created Pull Request!!! ❌❌❌:  Pull Request message: ${{ github.event.commits[0].message }}"
          
          
      - name: Telegram Notifications on Success
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            ${{ github.actor }} successfully created Pull Request!!! ✅✅✅:
              Pull Request message: ${{ github.event.commits[0].message }}
              Repository: ${{ github.repository }}
              See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}


      - name: Telegram Notifications on Failure
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            ${{ github.actor }} failed created Pull Request!!! ❌❌❌:
              Pull Request message: ${{ github.event.commits[0].message }}
              Repository: ${{ github.repository }}
              See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}